name: Install Python
description: Action for installing Python and uv

inputs:
  PYTHON_VERSION:
    description: "Version of Python to install"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.PYTHON_VERSION }}

    - name: Install uv and package dependencies
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        make install
      shell: bash
