name: Install Python
description: Action for installing Python and PDM

inputs:
  PYTHON_VERSION:
    description: "Version of Python to install"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.PYTHON_VERSION }}

    - name: Install PDM and package dependencies
      run: |
        pip install pdm
        make install
      shell: bash
