name: Install Python
description: Action for installing Python and Poetry

inputs:
  PYTHON_VERSION:
    description: "Version of Python to install"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.PYTHON_VERSION }}

    - name: Load Cached pyenv
      id: pyenv-cache
      uses: actions/cache@v3
      with:
        path: /opt/hostedtoolcache/pyenv_root
        key: pyenv-${{ runner.os }}-${{ inputs.PYTHON_VERSION }}

    - name: Install pyenv
      if: steps.pyenv-cache.outputs.cache-hit != 'true'
      uses: gabrielfalcao/pyenv-action@v17
      with:
        default: "${{ inputs.PYTHON_VERSION }}"
        command: pyenv global ${{ inputs.PYTHON_VERSION }}

    - name: Install PDM
      uses: pdm-project/setup-pdm@v3
      with:
        python-version: ${{ inputs.PYTHON_VERSION }}

    - name: Load Cached Virtualenv
      id: venv-cache
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ inputs.PYTHON_VERSION }}-${{ runner.os }}-${{ hashFiles('**/pyproject.toml', '**/poetry.lock') }}

    - name: Install dependencies and project in dev mode
      if: steps.venv-cache.outputs.cache-hit != 'true'
      run: make install
      shell: bash
