name: Install R and packages
description: Action for installing R and packages

inputs:
  R_VERSION:
    description: "Version of R to install"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install R
      uses: r-lib/actions/setup-r@v2

    - name: Install R packages
      run: |
        R_HOME=$(Rscript -e 'cat(R.home(component = "home"), fill=TRUE)')
        R_PROFILE_SITE="$R_HOME"/etc/Rprofile.site
        cat .github/actions/install-r/Rprofile.site | sudo tee -a $R_PROFILE_SITE
        Rscript -e 'install.packages("renv")'
      shell: bash
