name: Install R and packages
description: Action for installing R and packages

inputs:
  R_VERSION:
    description: "Version of R to install"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install R
      uses: r-lib/actions/setup-r@v2

    - name: Install Pandoc
      run: sudo apt install pandoc
      shell: bash

    - name: Install R packages
      run: |
        echo " \
          options(
            repos=c(CRAN=\"https://packagemanager.posit.co/cran/__linux__/jammy/2024-09-07'), \
            HTTPUserAgent = sprintf('R/%s R (%s)'', getRversion(), paste(getRversion(), R.version['platform'], R.version['arch'], R.version['os'])), \
            download.file.extra = sprintf('--header \"User-Agent: R (%s)\"', paste(getRversion(), R.version['platform'], R.version['arch'], R.version['os'])) \
        )" >> ~/.Rprofile
        Rscript -e 'install.packages(c("reticulate")'
      shell: bash
