name: Install R and packages
description: Action for installing R and packages

inputs:
  R_VERSION:
    description: "Version of R to install"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install R
      uses: r-lib/actions/setup-r@v2

    - name: Install Pandoc
      run: sudo apt install pandoc
      shell: bash

    - name: Install R packages
      run: |
        Rscript -e 'install.packages(c("rmarkdown", "renv", "yaml", "reticulate"), repos="https://packagemanager.posit.co/cran/__linux__/focal/2023-12-01")'
      shell: bash
